### ISSUE TITLE
Unable to save 

### ISSUE THREAD

**Issue by cortopy** [juhaku/loginized#13]
I can't see any images when I select a theme, and then when I select one and save I get this error

```
cp: cannot stat '/home/cortopy/.config/Loginized/false': No such file or directory /opt/Loginized/loginized-cli.sh: line 238: [: ==: unary operator expected
```

**Comment by juhaku** [comment]
Seems, really interesting I'm suspecting bug in code of latest two versions. Which distribution you are running? You could try out version `1.2.2` in meantime to see if the issue persist. 

And if you could tell me the setup you used there with the application. You opened the application and then chose some theme and pressed save? Once I know the setup I can fix asap.

The images won't be visible from anywhere by default. They are resources that can be additionally setup for the login screen by selecting them in the same way as would a theme be selected. Then the selected images will be placed into the selected theme.

**Comment by juhaku** [comment]
This bug surfaced due recent changes in code and was effective when save was executed without background image being selected. This is now being fixed and new release will be out in no time.

**Comment by cortopy** [comment]
all working great!!! thanks!!
