### ISSUE TITLE
Ubuntu 18.04 Question

### ISSUE THREAD

**Issue by serapis5** [juhaku/loginized#3]
Hi:
Have been using Loginized for some time now, but just upgraded to Ubuntu 18.04 and it no longer works.  I made sure libglib2.0-bin is installed but still get "...line 164: glib-compile-resources: command not found cp: cannot stat "/tmp/shell/theme/gnome-shell-theme.gresource': no such file or directory." " Just wondering if you have a workaround for this or will be updating soon.  I absolutely love this program.

Thanks

**Comment by juhaku** [comment]
Thanks for your feedback.. I'll start testing it and get back as soon as I have resolution for it.

**Comment by juhaku** [comment]
Hi, and it's really pleasure to here that it has been useful application and that you have liked it. Starting from ubuntu 18.04 required command is found from `libglib2.0-dev-bin` package as previously it was in `libglib2.0-bin` package.
After installing that package everything should run as smoothly as before. 
I tested it with fresh install of ubuntu 18.04. As Im not ubuntu user so I haven't noticed anything weird.
