### ISSUE TITLE
Install on Gentoo

### ISSUE THREAD

**Issue by mansoormemon** [juhaku/loginized#34]
How can I install this on gentoo (with systemd).

**Comment by juhaku** [comment]
I have never tried to install it on gentoo. But it depends on what package manager it is using. If none of the existing installers can be used then I suppose the zip file can be used. Zip is selfcontained package and only extracting the content to folder you want should be sufficient. As what comes to systemd I suppose the majority of the linuxes are running nowadays with systemd. This application is not intented to used in connection of systemd in any manner. It is just a tool that can be used externally via command line or GUI. If you wish to use the commandline application with systemd in the way that on boot the systemd would start some process that runs some commands from the commandline version of the Loginized, then you could write a systemd unit file that can be started via systemd.

**Comment by mansoormemon** [comment]
[Solved] Replace gentoo with arch.
