### ISSUE TITLE
Getting an error when saving theme

### ISSUE THREAD

**Issue by jasonames42** [juhaku/loginized#6]
/usr/lib/Loginized/resources/app/src/../loginized-cli.sh: line 128: /tmp/shell/theme/extensions/ubuntu-dock@ubuntu.com/yaru.css: No such file or directory /usr/lib/Loginized/resources/app/src/../loginized-cli.sh: line 128: /tmp/shell/theme/modes/yaru.json: No such file or directory

Compiled the Yaru theme, when I select it and hit save, the above error comes up. I checked the tmp folder, and the modes folder is not getting copied to tmp, but the file exists in the /usr/share/theme/yaru... etc.

Using Manjaro Gnome stable, up to date as of posting.

**Comment by juhaku** [comment]
Thanks for your notice. Could you possibly provide me the theme file what you were trying to use via comment to this thread attaching the file in the comment?

I'll get back to this when I get some sort of resolution to this.

**Comment by juhaku** [comment]
@jasonames42 I did some investigation on this issue and everything works without any issues on my machine. I did test this on latest manjaro and with latest release 1.0.0 loginized application. there might be an error in process to create gnome shell resource from correct files..  It is really necessary to have correct file set to create the login theme. 

To install Yaru theme as login theme in Manjaro latest stable Gnome you can follow these steps to complete this.
1. Download latest loginized application
     1. Open the application --> settings --> install the __loginized-cli__
2. Install `yaru-gnome-shell-theme` from AUR repository
3. Browse to folder `/usr/share/gnome-shell/theme` you will see there a folder named __Yaru__
    1. Copy this folder to `/usr/share/themes/`
    2. Create folder named `gnome-shell` in it and then move all the content into the folder
    3. Outcome is that you will have folder `/usr/share/themes/Yaru/gnome-shell/` which contains all the theme files required by login theme.
4. Now run following command `# loginized-cli compile .` in folder `/usr/share/themes/Yaru/gnome-shell/`
     1. Now there is 2 more files generated. __gnome-shell-theme.gresource.xml__ and __gnome-shell-theme.gresource__ file itself.
      2. This is good since now you can see this theme in __loginized__ application or in __Gnome Tweak tool__
5. Open loginized application and select the Yaru theme from the list and press Save.
6. :tada: It works!

**Comment by juhaku** [comment]
Also install the `yaru-gtk-theme` also if you wish to use the Yaru theme for the applications as well!
