### ISSUE TITLE
Ubuntu 18.10 / Gnome Shell 3.30.1: Does not change lock screen theme or login/lock screen image

### ISSUE THREAD

**Issue by logix2** [juhaku/loginized#8]
I'm using Ubuntu 18.10 / Gnome Shell 3.30.1 and Loginized 1.1.1. The login screen theme changes properly using Loginized. But the lock screen remains unchanged. Also, changing the login or lock screen image does not work.

**Comment by juhaku** [comment]
I installed ubuntu 18.10 for myself to virtual machine. In my environment it works without any issues.
It's running Xorg (x11) and is gnome-shell 3.30.1. Here's the screenshot's of it:
In this image only background was changed
![image](https://user-images.githubusercontent.com/26358664/50795876-56cca980-12d8-11e9-8899-0967b8d68cf8.png)
Here the theme was changed to Adapta-Nokto and background kept the same
![image](https://user-images.githubusercontent.com/26358664/50796011-d3f81e80-12d8-11e9-95d4-dd837d995eec.png)
But however I have noticed this kind of issue with latest openSUSE thumbleweed which is fairly puzzling to me. As same application with same functionality works fully in other not partly in other. This really makes me wonder why. Currently I don't know how to solve this.

**Comment by juhaku** [comment]
Important part in Ubuntu is that.. gdm3.css file in /etc/alternatives is linked to file in /usr/share/gnome-shell/theme. You can try to search your background's name from the file. If file name is there then it should have the background. The actual theme file that will be changed by each save is the /usr/share/gnome-shell/gnome-shell-theme.gresource file.

**Comment by logix2** [comment]
Weird, after a couple of more reboots it works now for the login screen. The purple lock screen background (the one that appears after pressing space, when you have to input your password, is still unchanged. Is Loginized supposed to change that, or only the image that appears before that screen (that one that has notifications on top of it)?

**Comment by juhaku** [comment]
Good to hear.. There are 2 pictures it should change.. When you are at login screen it should change the background as you can see in above pictures. Also this same login screen background is shown as background for the lock screen when you lock the computer.. 

The second picture that the Loginized will change is the lock screen image (Shield) for login. The shield that is shown in locks screen is not managed by the Loginized. That one need to be changed from System Settings -> Background -> Lock Screen.

The shield actually will only appear at login screen not in lock screen. So times when you first login to computer or when you have logged out and then about to loging again due inactivity the shield will appear.

The shield that appears in lock screen (when you lock the computer) is managed in system settings as described above. 

So to conclude. Login background is show in both screens. But the shield is shown only in the login screen. Not in the screen where you see the notifications above the user input.

**Comment by logix2** [comment]
So if I understand correctly, it should change the image for both the login screen and lock screen password input/unlock screen. But for me in Ubuntu 18.10 it only changes the login screen, the lock screen login background remains the same, like in this screenshot: [https://i.imgur.com/OMvl0vv.png](https://i.imgur.com/OMvl0vv.png) (taken in a virtual machine as I don't know how to take a screenshot of my actual lock screen).

**Comment by logix2** [comment]
Is that on Ubuntu 18.10? If so, I guess this may be some particularity on my system, so you can close this...

**Comment by juhaku** [comment]
Yes this is fresh install of minimal Ubuntu 18.10.
