### ISSUE TITLE
Save fails, if selected image file name contains spaces

### ISSUE THREAD

**Issue by klausahrenberg** [juhaku/loginized#9]
Hi, first thanks for this useful program. I detected a small issue. If you drag and drop some images to the program and the file name contains spaces, you are not able to save the boot screen, an error 'file or directory not found' occurs. After I removed the spaces in the file name and dragged the image again, all went fine.
E.g. for image named '2013-08-09 20.23.19', the following error message come up, when you try to save: 'Error - cp: der Aufruf von stat für '/home/[...]/.config/Loginized/2013-08-09' ist nicht möglich: Datei oder Verzeichnis nicht gefunden /opt/Loginized/loginized-cli.sh: Zeile 291: [: ==: Einstelliger (unärer) Operator erwartet.'

**Comment by juhaku** [comment]
Hello, thanks that you have liked it and also letting me know about the issue. I'll do some testing and patching up it a bit.  I'll let you know once fixed and new release is available.

**Comment by juhaku** [comment]
Fixed the bug realing this one. Now theme configurations can be saved with images having spaces in names as well. Newest release is available at [RELEASES](https://github.com/juhaku/loginized/releases)
